// automaticly generated by wsjcpp:v0.5.4

#include "__data_sample_html_images_attack_points_svg_path6352e9.h"

REGISTRY_WSJCPP_RESOURCE_FILE(RES___data_sample_html_images_attack_points_svg_path6352e9)

const std::string &RES___data_sample_html_images_attack_points_svg_path6352e9::getFilename() const {
    static const std::string s = "./data_sample/html/images/attack-points.svg";
    return s;
}
// ---------------------------------------------------------------------

const std::string &RES___data_sample_html_images_attack_points_svg_path6352e9::getPackAs() const {
    static const std::string s = "text";
    return s;
}
// ---------------------------------------------------------------------

int RES___data_sample_html_images_attack_points_svg_path6352e9::getBufferSize() const {
    return 4294;
}

// ---------------------------------------------------------------------

const char *RES___data_sample_html_images_attack_points_svg_path6352e9::getBuffer() const {
    static const std::string sRet = "" // size: 4294
        "<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"no\"?>\n"
        "<!-- Created with Inkscape (http://www.inkscape.org/) -->\n"
        "\n"
        "<svg\n"
        "   width=\"100\"\n"
        "   height=\"100\"\n"
        "   viewBox=\"0 0 26.458333 26.458334\"\n"
        "   version=\"1.1\"\n"
        "   id=\"svg8\"\n"
        "   inkscape:version=\"1.1.2 (0a00cf5339, 2022-02-04)\"\n"
        "   sodipodi:docname=\"attack-points.svg\"\n"
        "   xmlns:inkscape=\"http://www.inkscape.org/namespaces/inkscape\"\n"
        "   xmlns:sodipodi=\"http://sodipodi.sourceforge.net/DTD/sodipodi-0.dtd\"\n"
        "   xmlns=\"http://www.w3.org/2000/svg\"\n"
        "   xmlns:svg=\"http://www.w3.org/2000/svg\"\n"
        "   xmlns:rdf=\"http://www.w3.org/1999/02/22-rdf-syntax-ns#\"\n"
        "   xmlns:cc=\"http://creativecommons.org/ns#\"\n"
        "   xmlns:dc=\"http://purl.org/dc/elements/1.1/\">\n"
        "  <defs\n"
        "     id=\"defs2\" />\n"
        "  <sodipodi:namedview\n"
        "     id=\"base\"\n"
        "     pagecolor=\"#ffffff\"\n"
        "     bordercolor=\"#666666\"\n"
        "     borderopacity=\"1.0\"\n"
        "     inkscape:pageopacity=\"0.0\"\n"
        "     inkscape:pageshadow=\"2\"\n"
        "     inkscape:zoom=\"2.8\"\n"
        "     inkscape:cx=\"26.071429\"\n"
        "     inkscape:cy=\"58.035714\"\n"
        "     inkscape:document-units=\"px\"\n"
        "     inkscape:current-layer=\"layer1\"\n"
        "     showgrid=\"false\"\n"
        "     units=\"px\"\n"
        "     inkscape:window-width=\"2490\"\n"
        "     inkscape:window-height=\"1376\"\n"
        "     inkscape:window-x=\"70\"\n"
        "     inkscape:window-y=\"27\"\n"
        "     inkscape:window-maximized=\"1\"\n"
        "     inkscape:snap-global=\"false\"\n"
        "     inkscape:pagecheckerboard=\"0\" />\n"
        "  <metadata\n"
        "     id=\"metadata5\">\n"
        "    <rdf:RDF>\n"
        "      <cc:Work\n"
        "         rdf:about=\"\">\n"
        "        <dc:format>image/svg+xml</dc:format>\n"
        "        <dc:type\n"
        "           rdf:resource=\"http://purl.org/dc/dcmitype/StillImage\" />\n"
        "      </cc:Work>\n"
        "    </rdf:RDF>\n"
        "  </metadata>\n"
        "  <g\n"
        "     inkscape:label=\"Layer 1\"\n"
        "     inkscape:groupmode=\"layer\"\n"
        "     id=\"layer1\"\n"
        "     transform=\"translate(0,-270.54166)\">\n"
        "    <g\n"
        "       transform=\"translate(0,-198.96085)\"\n"
        "       id=\"layer1-3\"\n"
        "       inkscape:label=\"Layer 1\" />\n"
        "    <g\n"
        "       transform=\"translate(0,-198.96085)\"\n"
        "       id=\"layer1-1\"\n"
        "       inkscape:label=\"Layer 1\" />\n"
        "    <path\n"
        "       id=\"path870\"\n"
        "       style=\"fill:#cc5914;fill-opacity:1;fill-rule:evenodd;stroke:none;stroke-width:0.264583px;stroke-linecap:butt;stroke-linejoin:miter;stroke-opacity:1\"\n"
        "       d=\"m 1.4019611,271.32368 c 3.330102,5.25249 7.375941,10.89776 15.5592569,18.81332 l -2.86494,2.16214 1.201992,1.39733 3.681946,-3.40599 4.247804,4.21215 0.629417,1.83348 2.461866,-2.67684 -1.562695,-0.45941 -4.462778,-4.27674 3.517099,-3.66799 -1.411801,-1.50637 -1.860868,3.02876 C 14.242542,280.97554 7.9007871,275.53294 1.4019611,271.32368 Z m 24.3778409,0.21652 c -4.020595,2.34554 -8.100272,4.56276 -11.493873,8.26513 l 3.170348,2.96003 c 3.735872,-3.93704 5.866659,-7.54807 8.323525,-11.22516 z m -20.9232709,12.3145 -1.435571,1.48466 3.517098,3.53054 -4.280876,4.1615 -1.78335404,0.7922 2.61637804,2.57658 0.451652,-1.74201 4.381128,-4.41161 3.4618049,3.47989 1.473811,-1.37511 -3.042192,-2.16731 2.825152,-2.66082 -3.3150439,-3.37344 -2.770891,2.85047 z\" />\n"
        "    <g\n"
        "       id=\"g831\"\n"
        "       transform=\"matrix(0.59023936,0,0,0.54947771,10.764814,133.8179)\">\n"
        "      <path\n"
        "         style=\"fill:#ffe600;fill-opacity:1;fill-rule:evenodd;stroke:#000000;stroke-width:0.334308px;stroke-linecap:butt;stroke-linejoin:miter;stroke-opacity:1\"\n"
        "         d=\"m 4.522599,289.63405 2.3282191,-7.04435 -6.02949182,-4.17886 7.16375252,-0.1791 2.4476152,-6.86525 2.208825,7.04435 7.342847,0.0598 -5.850398,4.17886 2.387919,7.22345 -6.029495,-4.47734 z\"\n"
        "         id=\"path826-3\"\n"
        "         inkscape:connector-curvature=\"0\" />\n"
        "      <path\n"
        "         style=\"fill:#ff6700;fill-opacity:1;fill-rule:evenodd;stroke:#000000;stroke-width:0.264583px;stroke-linecap:butt;stroke-linejoin:miter;stroke-opacity:1\"\n"
        "         d=\"m 13.708745,289.40582 1.842634,-5.57514 -4.77195,-3.3073 5.669643,-0.14174 1.937128,-5.4334 1.74814,5.57514 5.811384,0.0473 -4.630208,3.30729 1.889881,5.71689 -4.77195,-3.54352 z\"\n"
        "         id=\"path826\"\n"
        "         inkscape:connector-curvature=\"0\" />\n"
        "      <path\n"
        "         style=\"fill:#4be600;fill-opacity:1;fill-rule:evenodd;stroke:#000000;stroke-width:0.264583px;stroke-linecap:butt;stroke-linejoin:miter;stroke-opacity:1\"\n"
        "         d=\"m 7.3942979,296.36898 1.8426337,-5.57514 -4.7719497,-3.3073 5.6696431,-0.14174 1.937128,-5.4334 1.74814,5.57514 5.811384,0.0473 -4.630208,3.30729 1.889881,5.71689 -4.77195,-3.54352 z\"\n"
        "         id=\"path826-6\"\n"
        "         inkscape:connector-curvature=\"0\" />\n"
        "    </g>\n"
        "  </g>\n"
        "</svg>\n"
        ""
    ;
    return sRet.c_str();
} //::buffer() 


