// automaticly generated by wsjcpp:v0.5.3

#include "__data_sample_html_images_defence_flags_svg_path8e463b.h"

REGISTRY_WSJCPP_RESOURCE_FILE(RES___data_sample_html_images_defence_flags_svg_path8e463b)

const std::string &RES___data_sample_html_images_defence_flags_svg_path8e463b::getFilename() const {
    static const std::string s = "./data_sample/html/images/defence-flags.svg";
    return s;
}
// ---------------------------------------------------------------------

const std::string &RES___data_sample_html_images_defence_flags_svg_path8e463b::getPackAs() const {
    static const std::string s = "text";
    return s;
}
// ---------------------------------------------------------------------

int RES___data_sample_html_images_defence_flags_svg_path8e463b::getBufferSize() const {
    return 3010;
}

// ---------------------------------------------------------------------

const char *RES___data_sample_html_images_defence_flags_svg_path8e463b::getBuffer() const {
    static const std::string sRet = "" // size: 3010
        "<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"no\"?>\n"
        "<!-- Created with Inkscape (http://www.inkscape.org/) -->\n"
        "\n"
        "<svg\n"
        "   width=\"100\"\n"
        "   height=\"100\"\n"
        "   viewBox=\"0 0 26.458333 26.458334\"\n"
        "   version=\"1.1\"\n"
        "   id=\"svg8\"\n"
        "   inkscape:version=\"1.1.2 (0a00cf5339, 2022-02-04)\"\n"
        "   sodipodi:docname=\"defence-flags.svg\"\n"
        "   xmlns:inkscape=\"http://www.inkscape.org/namespaces/inkscape\"\n"
        "   xmlns:sodipodi=\"http://sodipodi.sourceforge.net/DTD/sodipodi-0.dtd\"\n"
        "   xmlns=\"http://www.w3.org/2000/svg\"\n"
        "   xmlns:svg=\"http://www.w3.org/2000/svg\"\n"
        "   xmlns:rdf=\"http://www.w3.org/1999/02/22-rdf-syntax-ns#\"\n"
        "   xmlns:cc=\"http://creativecommons.org/ns#\"\n"
        "   xmlns:dc=\"http://purl.org/dc/elements/1.1/\">\n"
        "  <defs\n"
        "     id=\"defs2\" />\n"
        "  <sodipodi:namedview\n"
        "     id=\"base\"\n"
        "     pagecolor=\"#ffffff\"\n"
        "     bordercolor=\"#666666\"\n"
        "     borderopacity=\"1.0\"\n"
        "     inkscape:pageopacity=\"0.0\"\n"
        "     inkscape:pageshadow=\"2\"\n"
        "     inkscape:zoom=\"5.6\"\n"
        "     inkscape:cx=\"58.125\"\n"
        "     inkscape:cy=\"99.732143\"\n"
        "     inkscape:document-units=\"px\"\n"
        "     inkscape:current-layer=\"layer1\"\n"
        "     showgrid=\"false\"\n"
        "     units=\"mm\"\n"
        "     inkscape:window-width=\"1553\"\n"
        "     inkscape:window-height=\"1082\"\n"
        "     inkscape:window-x=\"422\"\n"
        "     inkscape:window-y=\"64\"\n"
        "     inkscape:window-maximized=\"0\"\n"
        "     inkscape:snap-global=\"false\"\n"
        "     inkscape:pagecheckerboard=\"0\" />\n"
        "  <metadata\n"
        "     id=\"metadata5\">\n"
        "    <rdf:RDF>\n"
        "      <cc:Work\n"
        "         rdf:about=\"\">\n"
        "        <dc:format>image/svg+xml</dc:format>\n"
        "        <dc:type\n"
        "           rdf:resource=\"http://purl.org/dc/dcmitype/StillImage\" />\n"
        "      </cc:Work>\n"
        "    </rdf:RDF>\n"
        "  </metadata>\n"
        "  <g\n"
        "     inkscape:label=\"Layer 1\"\n"
        "     inkscape:groupmode=\"layer\"\n"
        "     id=\"layer1\"\n"
        "     transform=\"translate(0,-270.54166)\">\n"
        "    <g\n"
        "       transform=\"translate(0,-198.96085)\"\n"
        "       id=\"layer1-3\"\n"
        "       inkscape:label=\"Layer 1\" />\n"
        "    <g\n"
        "       transform=\"translate(0,-198.96085)\"\n"
        "       id=\"layer1-1\"\n"
        "       inkscape:label=\"Layer 1\" />\n"
        "    <path\n"
        "       id=\"path889\"\n"
        "       style=\"fill:#00b100;fill-opacity:1;fill-rule:evenodd;stroke:none;stroke-width:0.999999px;stroke-linecap:butt;stroke-linejoin:miter;stroke-opacity:1\"\n"
        "       d=\"M 49.017578,0.53320312 C 36.984208,8.9310109 24.100453,16.1826 8.2695312,19.457031 6.815993,66.754228 28.477786,82.090542 49.253906,98.650391 72.485615,82.448728 91.284984,61.461745 90.751953,19.603516 74.228456,16.749179 61.696498,8.5427779 49.017578,0.53320312 Z M 49.238281,6.3789062 C 60.093141,14.710005 72.602536,19.357732 85.384766,23.400391 83.176777,65.726412 65.735624,79.111809 48.658203,93.189453 23.272101,73.716193 12.864958,49.780764 12.867188,22.744141 26.10924,20.474459 37.701363,13.505735 49.238281,6.3789062 Z m -0.30664,6.3261718 c -8.207392,7.1808 -18.577128,11.519808 -30.06836,14.384766 -0.675571,33.206475 16.755068,48.043763 30.25,59.3125 C 80.47263,59.853468 78.67596,43.963656 79.568359,27.210938 68.699459,25.145123 58.676128,19.512688 48.931641,12.705078 Z\"\n"
        "       transform=\"matrix(0.26458333,0,0,0.26458333,0,270.54166)\"\n"
        "       sodipodi:nodetypes=\"ccccccccccccccc\" />\n"
        "  </g>\n"
        "</svg>\n"
        ""
    ;
    return sRet.c_str();
} //::buffer() 


