// automaticly generated by wsjcpp:v0.5.5

#include <wsjcpp_core.h>

class RES___data_sample_html_font_LICENSE_path87d5e1 : public WsjcppResourceFile { 
    public:
        virtual const std::string &getFilename() const override;
        virtual const std::string &getPackAs() const override;
        virtual int getBufferSize() const override;
        virtual const char *getBuffer() const override;
};


