// automaticly generated by wsjcpp:v0.5.4

#include "__data_sample_html_images_defence_points_svg_path5ccfa0.h"

REGISTRY_WSJCPP_RESOURCE_FILE(RES___data_sample_html_images_defence_points_svg_path5ccfa0)

const std::string &RES___data_sample_html_images_defence_points_svg_path5ccfa0::getFilename() const {
    static const std::string s = "./data_sample/html/images/defence-points.svg";
    return s;
}
// ---------------------------------------------------------------------

const std::string &RES___data_sample_html_images_defence_points_svg_path5ccfa0::getPackAs() const {
    static const std::string s = "text";
    return s;
}
// ---------------------------------------------------------------------

int RES___data_sample_html_images_defence_points_svg_path5ccfa0::getBufferSize() const {
    return 4321;
}

// ---------------------------------------------------------------------

const char *RES___data_sample_html_images_defence_points_svg_path5ccfa0::getBuffer() const {
    static const std::string sRet = "" // size: 4321
        "<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"no\"?>\n"
        "<!-- Created with Inkscape (http://www.inkscape.org/) -->\n"
        "\n"
        "<svg\n"
        "   width=\"100\"\n"
        "   height=\"100\"\n"
        "   viewBox=\"0 0 26.458333 26.458334\"\n"
        "   version=\"1.1\"\n"
        "   id=\"svg8\"\n"
        "   inkscape:version=\"1.1.2 (0a00cf5339, 2022-02-04)\"\n"
        "   sodipodi:docname=\"defence-points.svg\"\n"
        "   xmlns:inkscape=\"http://www.inkscape.org/namespaces/inkscape\"\n"
        "   xmlns:sodipodi=\"http://sodipodi.sourceforge.net/DTD/sodipodi-0.dtd\"\n"
        "   xmlns=\"http://www.w3.org/2000/svg\"\n"
        "   xmlns:svg=\"http://www.w3.org/2000/svg\"\n"
        "   xmlns:rdf=\"http://www.w3.org/1999/02/22-rdf-syntax-ns#\"\n"
        "   xmlns:cc=\"http://creativecommons.org/ns#\"\n"
        "   xmlns:dc=\"http://purl.org/dc/elements/1.1/\">\n"
        "  <defs\n"
        "     id=\"defs2\" />\n"
        "  <sodipodi:namedview\n"
        "     id=\"base\"\n"
        "     pagecolor=\"#ffffff\"\n"
        "     bordercolor=\"#666666\"\n"
        "     borderopacity=\"1.0\"\n"
        "     inkscape:pageopacity=\"0.0\"\n"
        "     inkscape:pageshadow=\"2\"\n"
        "     inkscape:zoom=\"5.6\"\n"
        "     inkscape:cx=\"68.392857\"\n"
        "     inkscape:cy=\"61.339286\"\n"
        "     inkscape:document-units=\"px\"\n"
        "     inkscape:current-layer=\"layer1\"\n"
        "     showgrid=\"false\"\n"
        "     units=\"mm\"\n"
        "     inkscape:window-width=\"2490\"\n"
        "     inkscape:window-height=\"1376\"\n"
        "     inkscape:window-x=\"70\"\n"
        "     inkscape:window-y=\"27\"\n"
        "     inkscape:window-maximized=\"1\"\n"
        "     inkscape:snap-global=\"false\"\n"
        "     inkscape:pagecheckerboard=\"0\" />\n"
        "  <metadata\n"
        "     id=\"metadata5\">\n"
        "    <rdf:RDF>\n"
        "      <cc:Work\n"
        "         rdf:about=\"\">\n"
        "        <dc:format>image/svg+xml</dc:format>\n"
        "        <dc:type\n"
        "           rdf:resource=\"http://purl.org/dc/dcmitype/StillImage\" />\n"
        "      </cc:Work>\n"
        "    </rdf:RDF>\n"
        "  </metadata>\n"
        "  <g\n"
        "     inkscape:label=\"Layer 1\"\n"
        "     inkscape:groupmode=\"layer\"\n"
        "     id=\"layer1\"\n"
        "     transform=\"translate(0,-270.54166)\">\n"
        "    <g\n"
        "       transform=\"translate(0,-198.96085)\"\n"
        "       id=\"layer1-3\"\n"
        "       inkscape:label=\"Layer 1\" />\n"
        "    <g\n"
        "       transform=\"translate(0,-198.96085)\"\n"
        "       id=\"layer1-1\"\n"
        "       inkscape:label=\"Layer 1\" />\n"
        "    <path\n"
        "       id=\"path889\"\n"
        "       style=\"fill:#00b100;fill-opacity:1;fill-rule:evenodd;stroke:none;stroke-width:0.264583px;stroke-linecap:butt;stroke-linejoin:miter;stroke-opacity:1\"\n"
        "       d=\"m 13.47609,270.60128 c -3.183829,2.22192 -6.5926552,4.14057 -10.7812532,5.00693 -0.384582,12.51405 5.346767,16.57178 10.8437822,20.95324 6.146723,-4.28669 11.120722,-9.8395 10.979691,-20.91449 -4.371842,-0.75521 -7.687589,-2.92648 -11.04222,-5.04568 z m 0.0584,1.54667 c 2.872015,2.20427 6.181792,3.43398 9.563757,4.5036 -0.584197,11.19876 -5.198835,14.74032 -9.717236,18.46503 -6.7167402,-5.1523 -9.4702962,-11.48522 -9.4697062,-18.63866 3.503626,-0.60052 6.5707092,-2.44433 9.6231852,-4.32997 z m -0.08113,1.6738 c -2.171539,1.89992 -4.9151982,3.04795 -7.9555872,3.80597 -0.178745,8.78588 4.433112,12.71158 8.0036462,15.6931 8.297161,-7.02439 7.821792,-11.22857 8.057906,-15.66106 -2.87573,-0.54658 -5.527736,-2.03683 -8.105965,-3.83801 z\"\n"
        "       sodipodi:nodetypes=\"ccccccccccccccc\" />\n"
        "    <g\n"
        "       id=\"g831\"\n"
        "       transform=\"matrix(0.6563753,0,0,0.62729614,9.3208877,110.99935)\">\n"
        "      <path\n"
        "         style=\"fill:#ffe600;fill-opacity:1;fill-rule:evenodd;stroke:#000000;stroke-width:0.334308px;stroke-linecap:butt;stroke-linejoin:miter;stroke-opacity:1\"\n"
        "         d=\"m 4.522599,289.63405 2.3282191,-7.04435 -6.02949182,-4.17886 7.16375252,-0.1791 2.4476152,-6.86525 2.208825,7.04435 7.342847,0.0598 -5.850398,4.17886 2.387919,7.22345 -6.029495,-4.47734 z\"\n"
        "         id=\"path826-3\"\n"
        "         inkscape:connector-curvature=\"0\" />\n"
        "      <path\n"
        "         style=\"fill:#ff6700;fill-opacity:1;fill-rule:evenodd;stroke:#000000;stroke-width:0.264583px;stroke-linecap:butt;stroke-linejoin:miter;stroke-opacity:1\"\n"
        "         d=\"m 13.708745,289.40582 1.842634,-5.57514 -4.77195,-3.3073 5.669643,-0.14174 1.937128,-5.4334 1.74814,5.57514 5.811384,0.0473 -4.630208,3.30729 1.889881,5.71689 -4.77195,-3.54352 z\"\n"
        "         id=\"path826\"\n"
        "         inkscape:connector-curvature=\"0\" />\n"
        "      <path\n"
        "         style=\"fill:#4be600;fill-opacity:1;fill-rule:evenodd;stroke:#000000;stroke-width:0.264583px;stroke-linecap:butt;stroke-linejoin:miter;stroke-opacity:1\"\n"
        "         d=\"m 7.3942979,296.36898 1.8426337,-5.57514 -4.7719497,-3.3073 5.6696431,-0.14174 1.937128,-5.4334 1.74814,5.57514 5.811384,0.0473 -4.630208,3.30729 1.889881,5.71689 -4.77195,-3.54352 z\"\n"
        "         id=\"path826-6\"\n"
        "         inkscape:connector-curvature=\"0\" />\n"
        "    </g>\n"
        "  </g>\n"
        "</svg>\n"
        ""
    ;
    return sRet.c_str();
} //::buffer() 


