// automatically generated by wsjcpp:v0.6.1

#include "__data_sample_hv_logs__placeholder_path82cd15.h"

REGISTRY_WSJCPP_RESOURCE_FILE(RES___data_sample_hv_logs__placeholder_path82cd15)

const std::string &RES___data_sample_hv_logs__placeholder_path82cd15::getFilename() const {
  static const std::string s = "./data_sample/hv_logs/.placeholder";
  return s;
}
// ---------------------------------------------------------------------

const std::string &RES___data_sample_hv_logs__placeholder_path82cd15::getPackAs() const {
  static const std::string s = "binary";
  return s;
}
// ---------------------------------------------------------------------

int RES___data_sample_hv_logs__placeholder_path82cd15::getBufferSize() const {
  return 0;
}

// ---------------------------------------------------------------------

const char *RES___data_sample_hv_logs__placeholder_path82cd15::getBuffer() const {
  static const unsigned char b[0] = {
  };
  return (const char *)b;
} //::getBuffer()


