// automatically generated by wsjcpp:v0.2.7

#include <wsjcpp_core.h>

class RES___data_sample_checker_example_service5_checker_py_path443fce : public WsjcppResourceFile {
public:
  virtual const std::string &getFilename() const override;
  virtual const std::string &getPackAs() const override;
  virtual int getBufferSize() const override;
  virtual const char *getBuffer() const override;
};
