## Combined config for ctf01d
# use 2 spaces for tab

game:
  id: "test" # uniq gameid must be regexp [a-z0-9]+
  name: "Test First Game" # visible game name in scoreboard
  start_utc: "2025-11-12 16:00:00"
  end_utc: "2030-11-12 22:00:00"
  coffee_break_start: "2025-11-12 20:00:00"
  coffee_break_end: "2025-11-12 21:00:00"
  flag_lifetime_in_seconds: 60
  flag_cost_in_points: 100 # use a real number

scoreboard:
  port: 8080 # http port for scoreboard
  html-dir-path: "./html" # web page for scoreboard see index-template.html
  random: no # If yes - will be random values in scoreboard
  prometheus-metrics-endpoint:
    enabled: no
    allowed-for: "10.10.100.*, 127.0.*"

services:
  - id: "example_service1" # work directory will be checker_example_service4
    name: "Service1"
    enabled: yes
    logo: "./html/images/services/service17-default-icon.svg"
    logo-big: "./html/images/services/service17-default-icon.svg"
    # host: 127.0.0.1
    # port: 10001
    script-relative-path: "./checker.py"
    script-timeout-in-seconds: 5 # max time for running script
    round-in-seconds: 15
  - id: "example_service2" # work directory will be checker_example_service4
    name: "Service2"
    enabled: yes
    logo: "./html/images/services/service2-default-icon.svg"
    logo-big: "./html/images/services/service2-default-icon.svg"
    script-relative-path: "./checker.py"
    script-timeout-in-seconds: 5
    round-in-seconds: 15
  - id: "example_service3" # work directory will be checker_example_service4
    name: "Service3"
    enabled: yes
    logo: "./html/images/services/service26-default-icon.svg"
    logo-big: "./html/images/services/service26-default-icon.svg"
    script-relative-path: "./checker.py"
    script-timeout-in-seconds: 5
    round-in-seconds: 15
  - id: "example_service4" # work directory will be checker_example_service4
    name: "Service4"
    enabled: yes
    logo: "./html/images/services/service21-default-icon.svg"
    logo-big: "./html/images/services/service21-default-icon.svg"
    script-relative-path: "./checker.py"
    script-timeout-in-seconds: 5
    round-in-seconds: 15
  - id: "example_service5" # work directory will be checker_example_service4
    name: "Service5"
    enabled: yes
    logo: "./html/images/services/service6-default-icon.svg"
    logo-big: "./html/images/services/service6-default-icon.svg"
    script-relative-path: "./checker.py"
    script-timeout-in-seconds: 5
    round-in-seconds: 15
  - id: "example_service6" # work directory will be checker_example_service4
    name: "Service6"
    logo: "./html/images/services/service11-default-icon.svg"
    logo-big: "./html/images/services/service11-default-icon.svg"
    enabled: no
    script-relative-path: "./checker.py"
    script-timeout-in-seconds: 5
    round-in-seconds: 15

teams:
  config:
    ip-or-host-prefix: ""
    ip-or-host-suffix: ""
  list:
    - id: "t01" # must be uniq
      type: normal
      name: "Team #1"
      active: yes
      logo: "./html/images/teams/team01.png"
      logo-big: "./html/images/teams/team01.png"
      ip-or-host: "127.0.1.1"
    - id: "t02" # must be uniq
      type: normal
      name: "Team #2"
      active: yes
      logo: "./html/images/teams/team02.png"
      logo-big: "./html/images/teams/team02.png"
      ip-or-host: "127.0.2.1"
    - id: "t03" # must be uniq
      type: normal
      name: "Team #3"
      active: yes
      logo: "./html/images/teams/team03.png"
      logo-big: "./html/images/teams/team03.png"
      ip-or-host: "127.0.3.1"
    - id: "t04" # must be uniq
      type: normal
      name: "Team #4"
      active: yes
      logo: "./html/images/teams/team04.png"
      logo-big: "./html/images/teams/team03.png"
      ip-or-host: "127.0.4.1"
    - id: "t05" # must be uniq
      type: normal
      name: "Team #5"
      active: yes
      logo: "./html/images/teams/team05.png"
      logo-big: "./html/images/teams/team03.png"
      ip-or-host: "127.0.5.1"
    - id: "t06" # must be uniq
      type: normal
      name: "Team #6"
      active: yes
      logo: "./html/images/teams/team06.png"
      logo-big: "./html/images/teams/team06.png"
      ip-or-host: "127.0.6.1"
    - id: "t07" # must be uniq
      type: normal
      name: "Team #7"
      active: yes
      logo: "./html/images/teams/team07.png"
      logo-big: "./html/images/teams/team07.png"
      ip-or-host: "127.0.7.1"
    - id: "t08" # must be uniq
      type: normal
      name: "Team #8"
      active: yes
      logo: "./html/images/teams/team08.png"
      logo-big: "./html/images/teams/team08.png"
      ip-or-host: "127.0.8.1"
    - id: "t09" # must be uniq
      type: normal
      name: "Team #9"
      active: yes
      logo: "./html/images/teams/team09.png"
      logo-big: "./html/images/teams/team09.png"
      ip-or-host: "127.0.9.1"
    - id: "t10" # must be uniq
      type: normal
      name: "Team #10"
      active: yes
      logo: "./html/images/teams/team10.png"
      logo-big: "./html/images/teams/team10.png"
      ip-or-host: "127.0.10.1"
    - id: "t11" # must be uniq
      type: normal
      name: "Team #11"
      active: yes
      logo: "./html/images/teams/team11.png"
      logo-big: "./html/images/teams/team11.png"
      ip-or-host: "127.0.11.1"
    - id: "t12" # must be uniq
      type: normal
      name: "Team #12"
      active: yes
      logo: "./html/images/teams/team12.png"
      logo-big: "./html/images/teams/team12.png"
      ip-or-host: "127.0.12.1"
    - id: "t13" # must be uniq
      type: normal
      name: "Team #13"
      active: yes
      logo: "./html/images/teams/team13.png"
      logo-big: "./html/images/teams/team13.png"
      ip-or-host: "127.0.13.1"
    - id: "t14" # must be uniq
      type: normal
      name: "Team #14"
      active: yes
      logo: "./html/images/teams/team14.png"
      logo-big: "./html/images/teams/team14.png"
      ip-or-host: "127.0.14.1"
    - id: "t15" # must be uniq
      type: normal
      name: "Team #15"
      active: yes
      logo: "./html/images/teams/team15.png"
      logo-big: "./html/images/teams/team15.png"
      ip-or-host: "127.0.15.1"
    - id: "t16" # must be uniq
      type: normal
      name: "Team #16"
      active: yes
      logo: "./html/images/teams/team16.png"
      logo-big: "./html/images/teams/team16.png"
      ip-or-host: "127.0.16.1"
    - id: "t17" # must be uniq
      type: normal
      name: "Team #17"
      active: yes
      logo: "./html/images/teams/team17.png"
      logo-big: "./html/images/teams/team17.png"
      ip-or-host: "127.0.17.1"
    - id: "t18" # must be uniq
      type: normal
      name: "Team #18"
      active: yes
      logo: "./html/images/teams/team18.png"
      logo-big: "./html/images/teams/team18.png"
      ip-or-host: "127.0.18.1"
    - id: "t19" # must be uniq
      type: normal
      name: "Team #19"
      active: yes
      logo: "./html/images/teams/team19.png"
      logo-big: "./html/images/teams/team19.png"
      ip-or-host: "127.0.19.1"
    - id: "t20" # must be uniq
      type: normal
      name: "Team #20"
      active: yes
      logo: "./html/images/teams/team20.png"
      logo-big: "./html/images/teams/team20.png"
      ip-or-host: "127.0.20.1"
    - id: "t21" # must be uniq
      type: normal
      name: "Team #21"
      active: yes
      logo: "./html/images/teams/team21.png"
      logo-big: "./html/images/teams/team21.png"
      ip-or-host: "127.0.21.1"
    - id: "t22" # must be uniq
      type: normal
      name: "Team #22"
      active: yes
      logo: "./html/images/teams/team22.png"
      logo-big: "./html/images/teams/team22.png"
      ip-or-host: "127.0.22.1"
    - id: "t23" # must be uniq
      type: normal
      name: "Team #23"
      active: yes
      logo: "./html/images/teams/team23.png"
      logo-big: "./html/images/teams/team23.png"
      ip-or-host: "127.0.23.1"
    - id: "t24" # must be uniq
      type: normal
      name: "Team #24"
      active: yes
      logo: "./html/images/teams/team24.png"
      logo-big: "./html/images/teams/team24.png"
      ip-or-host: "127.0.24.1"
    - id: "t25" # must be uniq
      type: normal
      name: "Team #25"
      active: yes
      logo: "./html/images/teams/team25.png"
      logo-big: "./html/images/teams/team25.png"
      ip-or-host: "127.0.25.1"
    - id: "t26" # must be uniq
      type: normal
      name: "Team #26"
      active: yes
      logo: "./html/images/teams/team26.png"
      logo-big: "./html/images/teams/team26.png"
      ip-or-host: "127.0.26.1"
    - id: "t27" # must be uniq
      type: normal
      name: "Team #27"
      active: yes
      logo: "./html/images/teams/team27.png"
      logo-big: "./html/images/teams/team27.png"
      ip-or-host: "127.0.27.1"
    - id: "t28" # must be uniq
      type: normal
      name: "Team #28"
      active: yes
      logo: "./html/images/teams/team28.png"
      logo-big: "./html/images/teams/team28.png"
      ip-or-host: "127.0.28.1"
    - id: "t29" # must be uniq
      type: normal
      name: "Team #29"
      active: yes
      logo: "./html/images/teams/team29.png"
      logo-big: "./html/images/teams/team29.png"
      ip-or-host: "127.0.29.1"
    - id: "t30" # must be uniq
      type: normal
      name: "Team #30 1111111111111111111111111111111"
      active: yes
      logo: "./html/images/teams/team30.png"
      logo-big: "./html/images/teams/team30.png"
      ip-or-host: "192.168.88.3"
