// automatically generated by wsjcpp:v0.2.7

#include <wsjcpp_core.h>

class RES___data_sample_html_favicon_16x16_png_path5633bb : public WsjcppResourceFile {
public:
  virtual const std::string &getFilename() const override;
  virtual const std::string &getPackAs() const override;
  virtual int getBufferSize() const override;
  virtual const char *getBuffer() const override;
};
