FROM debian:12
# stage release
LABEL "maintainer"="Evgenii Sopov <mrseakg@gmail.com>"
LABEL "repository"="https://github.com/sea5kg/ctf01d"

RUN apt-get -y update && apt-get -y upgrade && apt-get install -y \
    libcurl4 \
    zlib1g \
    libpng16-16 \
    libpthread-stubs0-dev \
    libssl-dev \
    nano \
    vim \
    ruby-full \
    ruby-sqlite3 \
    python3 \
    python3-pip \
    python-is-python3 \
    telnet \
    iputils-ping \
    && python3 -m pip install --break-system-packages \
        requests \
        faker \
        grpcio \
        grpcio-tools \
        protobuf \
        tzdata \
        bs4 \
        mimesis
