FROM debian:13
WORKDIR /root/

# stage release
LABEL "maintainer"="Evgenii Sopov <mrseakg@gmail.com>"
LABEL "repository"="https://github.com/sea5kg/ctf01d"

RUN apt-get -y update \
    && apt-get -y upgrade \
    && apt-get install -y --no-install-recommends \
    libcurl4 \
    zlib1g \
    libpthread-stubs0-dev \
    locales \
    libpng16-16 \
    libssl-dev \
    nano \
    vim \
    python3 \
    python3-pip \
    python-is-python3 \
    telnet \
    iputils-ping \
    && python3 -m pip install --break-system-packages \
        requests \
        faker \
        grpcio \
        grpcio-tools \
        protobuf \
        tzdata \
        bs4 \
        mimesis \
    && apt-get clean

# RUN locale-gen en_US.UTF-8
RUN sed -i -e "s/# en_US.UTF-8 UTF-8/en_US.UTF-8 UTF-8/" /etc/locale.gen && \
    echo 'LANG="en_US.UTF-8"'>/etc/default/locale && \
    dpkg-reconfigure --frontend=noninteractive locales && \
    update-locale LANG=en_US.UTF-8