FROM debian:13
WORKDIR /root/

# stage build
LABEL "maintainer"="Evgenii Sopov <mrseakg@gmail.com>"
LABEL "repository"="https://github.com/sea5kg/ctf01d"

RUN apt-get -y update \
    && apt-get -y upgrade \
    && apt-get install -y --no-install-recommends \
    make \
    cmake \
    gcc \
    g++ \
    curl \
    pkg-config \
    libcurl4-openssl-dev \
    zlib1g zlib1g-dev \
    libpng-dev \
    python3 \
    python3-pip \
    && pip3 install --break-system-packages requests \
        faker \
    && apt-get clean
